---
# tasks file for roles/influxdb

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

# - name: Install all requemants packages
#   ansible.builtin.pip:
#     name: "{{ item }}"
#     state: latest
#   with_items: 
#     - "docker"
#     - "docker-compose"

- name: create dir for influxdb
  file:
    path: /home/influxdb
    state: directory
    mode: '0755'

- name: Copy Compose config file
  copy:
    src: files/
    dest: /home/influxdb

- name: Copy Compose file
  copy:
    src: templates/
    dest: /home/influxdb

- name: influxdb Compose Up
  docker_compose:
    project_src: /home/influxdb
    state: present