- name: System Update
  ansible.builtin.package:
    update_cache: true
    cache_valid_time: 3600

- name: Create user ubuntu
  ansible.builtin.user:
    name: ubuntu
    shell: /bin/bash
    groups: sudo, docker
    append: true

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Install all requemants packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
  with_items: 
    - "docker"
    - "docker-compose"

- name: create dir for influxdb
  file:
    path: /home/ubuntu/influxdb
    state: directory
    mode: '0755'
    group: ubuntu
    owner: ubuntu

- name: Copy Compose config file
  copy:
    src: files/
    dest: /home/ubuntu/influxdb

- name: Copy Compose file
  copy:
    src: templates/
    dest: /home/ubuntu/influxdb

- name: influxdb Compose Up
  docker_compose:
    project_src: /home/ubuntu/influxdb
    state: present