version: '2.0'
services:
  influxdb:
    image: "influxdb:2.7.10"
    restart: always
    environment:
      # You can define the admin user in the config file or use these for simple auth
      INFLUXDB_DB: telegraf
      INFLUXDB_ADMIN_USER: test
      INFLUXDB_ADMIN_PASSWORD: test123
    ports:
      - "8086:8086"
    networks:
      - influxdb_network
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - influxdb:/var/lib/influxdb
volumes:
  influxdb:
networks:
  influxdb_network:
