---
# tasks file for Grafana

- name: Install all requemants packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ Package }}"  

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip

- name: Install required Python packages
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: latest
    extra_args: "{{ item.extra_args | default('') }}"
  loop:
    - name: "docker==4.4.4"
    - name: "docker-compose==1.20.1"
      extra_args: "--no-deps"

- name: Create directory for Grafana
  ansible.builtin.file:
    path: /home/grafana
    state: directory
    mode: '0755'

- name: Copy Docker Compose config files
  ansible.builtin.copy:
    src: files/
    dest: /home/grafana/
    mode: '0644'

- name: Copy Docker Compose template files
  ansible.builtin.copy:
    src: templates/
    dest: /home/grafana/
    mode: '0644'

- name: Run Grafana using Docker Compose
  community.docker.docker_compose:
    project_src: /home/grafana
    state: present

# - name: setup Nginx-proxy
#   package:
#     name: nginx
#     state: present