---
- hosts: server #Centos #Ubuntu
  roles: 
    - Docker
    - Grafana
    - influxdb
    #- Graylog
    #- Nagios
    #- Wazuh
    #- Zabbix
# Monitor_agent List
    #- telegraf  # agents server
    #-