---
- hosts: server #Centos #Ubuntu
  roles: 
    # - geerlingguy.docker
    # - role: Grafana
    - role: influxdb
    #- Graylog
    #- Nagios
    #- Wazuh
    #- Zabbix
# Monitor_agent List
- hosts: agents
  roles:
    - geerlingguy.docker
    - role: telegraf          # Telegraf agent for collecting metrics
    #-