# version: "3.8"

# services:
#   mongodb:
#     image: "mongo:5.0"
#     volumes:
#       - "mongodb_data:/data/db"
#     restart: "on-failure"

#   opensearch:
#     image: "opensearchproject/opensearch:2.4.0"
#     environment:
#       - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
#       - "bootstrap.memory_lock=true"
#       - "discovery.type=single-node"
#       - "action.auto_create_index=false"
#       - "plugins.security.ssl.http.enabled=false"
#       - "plugins.security.disabled=true"
#     ulimits:
#       memlock:
#         hard: -1
#         soft: -1
#       nofile:
#         soft: 65536
#         hard: 65536
#     volumes:
#       - "os_data:/usr/share/opensearch/data"
#     restart: "on-failure"

#   graylog:
#     hostname: "server"
#     image: "${GRAYLOG_IMAGE:-graylog/graylog:5.0}"
#     depends_on:
#       opensearch:
#         condition: "service_started"
#       mongodb:
#         condition: "service_started"
#     entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
#     environment:
#       GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
#       GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET}"
#       GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2}"
#       GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
#       GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
#       GRAYLOG_ELASTICSEARCH_HOSTS: "http://localhost:9200"
#       GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
#     ports:
#     - "5044:5044/tcp"   # Beats
#     - "5140:5140/udp"   # Syslog
#     - "5140:5140/tcp"   # Syslog
#     - "5555:5555/tcp"   # RAW TCP
#     - "5555:5555/udp"   # RAW TCP
#     - "9000:9000/tcp"   # Server API
#     - "12201:12201/tcp" # GELF TCP
#     - "12201:12201/udp" # GELF UDP
#     #- "10000:10000/tcp" # Custom TCP port
#     #- "10000:10000/udp" # Custom UDP port
#     - "13301:13301/tcp" # Forwarder data
#     - "13302:13302/tcp" # Forwarder config
#     volumes:
#       - "graylog_data:/usr/share/graylog/data/data"
#       - "graylog_journal:/usr/share/graylog/data/journal"
#     restart: "on-failure"

# volumes:
#   mongodb_data:
#   os_data:
#   graylog_data:
#   graylog_journal:



# version: '3.8'

# services:
#   mongodb:
#     image: mongo:5.0
#     container_name: mongo
#     networks:
#       - graylog
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

#   opensearch:
#     image: opensearchproject/opensearch:2.4.0
#     container_name: opensearch
#     environment:
#       - cluster.name=graylog
#       - node.name=opensearch
#       - discovery.type=single-node
#       - bootstrap.memory_lock=true
#       - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     networks:
#       - graylog
#     ports:
#       - "9200:9200"
#       - "9600:9600"
#     volumes:
#       - opensearch_data:/usr/share/opensearch/data

#   graylog:
#     image: graylog/graylog:5.0
#     container_name: graylog
#     environment:
#       - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
#       - GRAYLOG_ROOT_PASSWORD_SHA2=<hashed-password>
#       - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
#       - GRAYLOG_MONGODB_URI=mongodb://mongo:27017/graylog
#       - GRAYLOG_OPENSEARCH_HOSTS=http://127.0.0.1:9200
#     depends_on:
#       - mongodb
#       - opensearch
#     networks:
#       - graylog
#     ports:
#       - "9000:9000"
#       - "12201:12201/udp"
#       - "5555:5555/udp"
#     volumes:
#       - graylog_journal:/usr/share/graylog/data/journal

# networks:
#   graylog:
#     driver: bridge

# volumes:
#   mongo_data:
#   opensearch_data:
#   graylog_journal:



version: '3' 
 
services: 
  # MongoDB: https://hub.docker.com/_/mongo/ 
  mongo: 
    image: mongo:5.0 
    container_name: mongodb 
    volumes: 
      - /home/graylog/mongodb:/data/db 
    networks: 
      - graylog 
 
  #elasticsearch
  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0 
    container_name: elasticsearch 
    environment: 
      - http.host=0.0.0.0 
      - transport.host=localhost 
      - network.host=0.0.0.0 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
    volumes: 
      - /home/graylog/elasticsearch:/usr/share/elastisearch/data 
    ulimits: 
      memlock: 
        soft: -1 
        hard: -1 
    deploy: 
      resources: 
        limits: 
          memory: 1g 
    ports: 
      - 9200:9200 
    networks: 
      - graylog 
 
  # Graylog: https://hub.docker.com/r/graylog/graylog/ 
  graylog: 
    image: graylog/graylog:5.0 
    container_name: graylog 
    environment: 
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/ 
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://localhost:9200 
      - GRAYLOG_ELASTICSEARCH_VERSION=7 
    volumes: 
      - /home/graylog/graylog:/usr/share/graylog/data 
    networks: 
      - graylog 
    restart: always 
    depends_on: 
      - mongo 
      - elasticsearch 
    ports: 
      # Graylog web interface and REST API 
      - 9000:9000 
      # Syslog TCP 
      - 514:1514 
      # Syslog UDP 
      - 514:1514/udp 
      # GELF TCP 
      - 12201:12201
 
networks: 
  graylog: