---
# tasks file for roles/telegraf

- name: Include Ubuntu tasks if the OS is Debian/Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Include RedHat tasks if the OS is RedHat/Rocky
  include_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"
